# Portainer docker-compose file
version: '3'
services:
    portainer:
        image: portainer/portainer:arm
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - portainer_data:/data
        ports:
            - 9000:9000

# Define volumes
volumes:
    portainer_data: