# Pulled from https://www.home-assistant.io/docs/installation/docker/#docker-compose
version: '3'
services:
    homeassistant:
        container_name: home-assistant
        image: homeassistant/home-assistant:latest
        volumes:
            - /home/pi/hass:/config
        environment:
            - TZ=America/New_York
        restart: always
        network_mode: host